version: '2'
services:
  easygo-app:
    image: easygo
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SPRING_PROFILES_ACTIVE=prod,swagger
      - MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED=true
      - SPRING_DATA_MONGODB_URI=mongodb://easygo-mongodb:27017
      - SPRING_DATA_MONGODB_DATABASE=easygo
      - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    ports:
      - 8080:8080
  easygo-mongodb:
    extends:
      file: mongodb.yml
      service: easygo-mongodb
